import type SimpleMarkerSymbol from "@arcgis/core/symbols/SimpleMarkerSymbol.js";
import type { Symbol3DColorMixMode } from "@arcgis/core/symbols/support/types";
import type {
  FillStyle,
  FontDecoration,
  FontStyle,
  FontWeight,
  IconSymbol3DLayerAnchor,
  IconSymbol3DLayerPrimitive,
  LineCap,
  LineJoin,
  LineMarkerPlacement,
  LineMarkerStyle,
  LineStyle,
  ObjectSymbol3DLayerAnchor,
  ObjectSymbol3DLayerPrimitiveType,
  PathSymbol3DLayerAnchor,
  PathSymbol3DLayerCap,
  PathSymbol3DLayerProfile,
  PathSymbol3DLayerProfileRotation,
  TextHorizontalAlignment,
  TextVerticalAlignment,
  WaterBodySize,
  WaveStrength,
} from "@arcgis/core/symbols/types";
import fontData from "./esri-labeling-page-data.json";

export const capOptions: LineCap[] = ["round", "butt", "square"];

export const cap3DOptions: PathSymbol3DLayerCap[] = [
  "butt",
  "square",
  "round",
  "none",
];

export const colorMixModeOptions: Symbol3DColorMixMode[] = [
  "multiply",
  "ignore",
  "replace",
  "tint",
];

export const esri2DPointSymbolsStyleNameOptions = [
  "extent-hollow-gray",
  "extent-hollow-square",
  "extent-hollow-square-yellow",
  "extent-square",
  "extent-square-gray",
  "extent-square-yellow",
  "extent-star",
  "extent-star-gray",
  "extent-star-yellow",
  "accessibility",
  "aerial-tram",
  "airport",
  "amusement-park",
  "aquarium",
  "atm",
  "bar",
  "beach",
  "border-crossing",
  "box-pin",
  "bus-station",
  "campground",
  "car-rental",
  "casino",
  "cemetery",
  "city-hall",
  "coffee-shop",
  "court-house",
  "embassy",
  "esri-pin-1",
  "esri-pin-2",
  "ferry",
  "fire-station",
  "flag",
  "gas-station",
  "golf-course",
  "grocery-store",
  "hospital",
  "hotel",
  "house",
  "industrial-complex",
  "information",
  "landmark",
  "library",
  "live-music-venue",
  "military-base",
  "mountain",
  "museum",
  "native-reservation",
  "park",
  "parking",
  "pharmacy",
  "place-of-worship",
  "playground",
  "police-station",
  "post-office",
  "push-pin-1",
  "push-pin-2",
  "radio-tower",
  "restaurant",
  "restroom",
  "school",
  "shopping-center",
  "sports-complex",
  "star",
  "subway-station",
  "tear-pin-1",
  "tear-pin-2",
  "theatre",
  "trail",
  "train-station",
  "university",
  "vineyard",
  "zoo",
  "circle-1",
  "circle-2",
  "circle-3",
  "circle-4",
  "circle-5",
  "circle-6",
  "cross-1",
  "cross-2",
  "cross-3",
  "cross-4",
  "diamond-1",
  "diamond-2",
  "diamond-3",
  "hexagon-1",
  "hexagon-2",
  "hexagon-3",
  "pentagon-1",
  "pentagon-2",
  "pentagon-3",
  "square-1",
  "square-2",
  "square-3",
  "square-4",
  "square-5",
  "square-6",
  "star-1",
  "star-2",
  "star-3",
  "triangle-1",
  "triangle-2",
  "triangle-3",
  "triangle-4",
  "triangle-5",
  "triangle-6",
  "shield-1",
  "shield-1-wide",
  "shield-2",
  "shield-3",
  "shield-4",
  "shield-5",
];

export const esriIconsStyleNameOptions = [
  "Accessibility",
  "Aerial Tram",
  "Airport",
  "Amusement Park",
  "Aquarium",
  "Bank",
  "Bar",
  "Beach",
  "Border Crossing",
  "Bus",
  "Campground",
  "Car Rental",
  "Casino",
  "Cemetery",
  "Centered Circle",
  "Centered Diamond",
  "Centered Diamond Wide",
  "Centered Hexagon",
  "Centered Octagon",
  "Centered Rounded Square",
  "Centered Square",
  "Centered Star",
  "Centered Triangle",
  "City Hall",
  "Coffee",
  "Court House",
  "Embassy",
  "Ferry",
  "Fire",
  "Flag",
  "Fuel",
  "Golf Course",
  "Grocery Store",
  "Hiking",
  "Hospital",
  "Hotel",
  "House",
  "Industrial Complex",
  "Information",
  "Landmark",
  "Library",
  "Live Music Venue",
  "Military Base",
  "Mountain",
  "Museum",
  "Native Reservation",
  "Park",
  "Parking",
  "Pharmacy",
  "Place of Worship",
  "Playground",
  "Police",
  "Post Office",
  "Pushpin 1",
  "Pushpin 2",
  "Pushpin 3",
  "Pushpin 4",
  "Pushpin 5",
  "Restaurant",
  "Restroom",
  "School",
  "Shopping",
  "Sports Complex",
  "Standing Circle",
  "Standing Diamond",
  "Standing Diamond Wide",
  "Standing Hexagon",
  "Standing Octagon",
  "Standing Rounded Square",
  "Standing Square",
  "Standing Star",
  "Standing Triangle",
  "Telecom",
  "Theatre",
  "Train",
  "University",
  "Vineyard",
  "Zoo",
];

export const esriInfrastructureStyleNameOptions = [
  "Cell_Phone_Antenna",
  "Electricity_Box",
  "Electricity_Meter",
  "Powerline_Pole",
  "Radio_Antenna",
  "Wind_Turbine",
];

export const esriRealisticSignsAndSignalsStyleNameOptions = [
  "Campfire",
  "Camping",
  "Crossroads",
  "Dead_End",
  "Do_Not_Enter",
  "Gas",
  "Left_T-junction",
  "Medical",
  "Motel",
  "No_Outlet",
  "No_Thru_Traffic",
  "Opposing_Traffic",
  "Pedestrian_Crossing",
  "Picnic_Area",
  "Railway_Crossing",
  "Restaurant",
  "Right_T-junction",
  "School_Crossing",
  "Speed_Limit_-_15_mph",
  "Speed_Limit_-_20_mph",
  "Speed_Limit_-_25_mph",
  "Speed_Limit_-_30_mph",
  "Speed_Limit_-_35_mph",
  "Speed_Limit_-_40_mph",
  "Speed_Limit_-_45_mph",
  "Speed_Limit_-_50_mph",
  "Speed_Limit_-_55_mph",
  "Speed_Limit_-_60_mph",
  "Speed_Limit_-_65_mph",
  "Speed_Limit_-_70_mph",
  "Stop",
  "Stop_Ahead",
  "T-Junction",
  "Telephone",
  "Traffic_Light",
  "Traffic_Light_1",
  "Traffic_Light_2",
  "Traffic_Light_3",
  "Traffic_Light_4",
  "Turn_Left_Arrow",
  "Turn_Right_Arrow",
  "Yield",
];

export const esriRealisticStreetSceneStyleNameOptions = [
  "ATM",
  "Bike_Rack",
  "Bus_Stop_1",
  "Bus_Stop_2",
  "Dumpster",
  "Fire_Hydrant",
  "Fountain_1",
  "Fountain_2",
  "Fountain_3",
  "Fountain_4",
  "Jersey_Barrier",
  "Light_On_Post_-_Light_off",
  "Light_On_Post_-_Light_on",
  "Mailbox",
  "Newspaper_Vending_Machine",
  "Overhanging_Sidewalk_-_Light_off",
  "Overhanging_Sidewalk_-_Light_on",
  "Overhanging_Street_-_Light_off",
  "Overhanging_Street_-_Light_on",
  "Overhanging_Street_and_Sidewalk_-_Light_off",
  "Overhanging_Street_and_Sidewalk_-_Light_on",
  "Park_Bench_1",
  "Park_Bench_2",
  "Park_Bench_3",
  "Park_Bench_4",
  "Payphone",
  "Picnic_Table",
  "Planter_Circular",
  "Planter_Square",
  "Planter_Tapered",
  "Rock_1",
  "Rock_2",
  "Rock_3",
  "Rock_4",
  "Sewer_Grate",
  "Storm_Drain",
  "Traffic_Barrier_1",
  "Traffic_Barrier_2",
  "Traffic_Cone",
  "Traffic_Pylon",
  "Trash_Bin_1",
  "Trash_Bin_2",
  "Trash_Bin_3",
  "Trash_Can_1",
  "Trash_Can_2",
  "US_Mailbox",
];

export const esriRealisticTransportationStyleNameOptions = [
  "Airplane_Large_Passenger",
  "Airplane_Large_Passenger_With_Wheels",
  "Airplane_Private",
  "Airplane_Private_With_Wheels",
  "Airplane_Propeller",
  "Airplane_Propeller_With_Wheels",
  "Airplane_Small_Passenger",
  "Airplane_Small_Passenger_With_Wheels",
  "Ambulance",
  "Audi_A6",
  "BMW_3-Series",
  "Backhoe",
  "Bobcat",
  "Bus",
  "Cargo_Box",
  "Cargo_Ship_Empty",
  "Cargo_Ship_Full",
  "City_Bike",
  "Crane",
  "Delivery_Truck",
  "Dumptruck",
  "Eurocopter_AS-365",
  "Eurocopter_AS-365_-_Flying",
  "Eurocopter_H125",
  "Eurocopter_H125_-_Flying",
  "Firetruck",
  "Ford_Edge",
  "Ford_Expedition",
  "Ford_F-150",
  "Ford_Fiesta",
  "Ford_Focus_Hatchback",
  "Ford_Fusion",
  "Ford_Mustang",
  "Ford_Taurus",
  "Ford_Transit_Commercial_Van",
  "Ford_Transit_Connect",
  "High_Speed_Train",
  "Mercedes_S-Class",
  "Motorboat",
  "Motorcycle",
  "Mountain_Bike",
  "Pickup_Truck_Ford_F250",
  "Pickup_Truck_Toyota_Hilux",
  "Police",
  "Porsche_Boxter",
  "Porsche_Carrera",
  "Road_Bike",
  "Sailboat",
  "Sailboat_-_Sails_Up",
  "Semi_Trailer_Truck",
  "Taxi",
  "Tesla_P7",
  "Tower_Crane",
  "Toyota_Prius",
  "Tractor",
  "Tractor_And_Trailer",
  "Trailer",
  "Train_Europe",
  "Train_Europe_With_Carriages",
  "Train_US",
  "Tram",
  "Tricycle",
  "Truck_With_Trailer",
  "Van_Taxi",
  "Volkswagen_Jetta_Wagon",
];

export const esriRealisticTreesStyleNameOptions = [
  "Frangula",
  "Echinodorus",
  "Castanea",
  "Platanus",
  "Prunus",
  "Casuarina",
  "Taxodium",
  "Abies",
  "Phyllostachys",
  "Musa",
  "Tilia",
  "Laurus",
  "Robinia",
  "Eucalyptus",
  "Buxus",
  "Phlebodium",
  "Umbellularia",
  "Calocedrus",
  "Washingtonia",
  "Sequoia",
  "Juglans",
  "Cocos",
  "Crataegus",
  "Sorbus",
  "Aesculus",
  "Phoenix",
  "Chilopsis",
  "Pseudotsuga",
  "Fagus",
  "Larix",
  "Ficus",
  "Ulmus",
  "Fremontodendron",
  "Cornus",
  "GenericDead",
  "Stump",
  "Unknown",
  "Sequoiadendron",
  "Agave",
  "Aralia",
  "Philodendron",
  "Cupressus",
  "Convallaria",
  "Pinus",
  "Rhamnus",
  "Sabal",
  "Cercocarpus",
  "Quercus Rubra",
  "Acer",
  "Picea",
  "Citrus",
  "Bulbophyllum",
  "Other",
  "Ligustrum",
  "Cordyline",
  "Parkinsonia",
  "Betula",
  "Chamaedorea",
  "Opuntia",
  "Alnus",
  "Carya",
  "Rhododendron",
  "Rosa",
  "Aiphanes",
  "Carnegiea",
  "Sassafras",
  "Pinus Sylvestris",
  "Yucca",
  "Amelanchier",
  "Sansevieria",
  "Magnolia",
  "Spartium",
  "Arbutus",
  "Acer Saccharum",
  "Helianthus",
  "Liquidambar",
  "Acacia",
  "Juniperus",
  "Fraxinus",
  "Quercus",
  "Populus",
  "Salix",
  "Hamamelis",
];

export const esriRecreationStyleNameOptions = [
  "American_Football_Goal",
  "Basketball_Hoop",
  "Jungle_Gym",
  "Slide",
  "Soccer_Goal",
  "Swing",
  "Teeter_Totter",
];

export const esriThematicShapesStyleNameOptions = [
  "Centered Cube",
  "Centered Diamond",
  "Centered Sphere",
  "Standing Cone",
  "Standing Cube",
  "Standing Cylinder",
  "Standing Diamond",
  "Standing Inverted Cone",
  "Standing Sphere",
  "Standing Tetrahedron",
];

export const esriThematicTreesStyleNameOptions = [
  "Frangula",
  "Echinodorus",
  "Castanea",
  "Platanus",
  "Prunus",
  "Casuarina",
  "Taxodium",
  "Abies",
  "Phyllostachys",
  "Musa",
  "Tilia",
  "Laurus",
  "Robinia",
  "Eucalyptus",
  "Buxus",
  "Phlebodium",
  "Umbellularia",
  "Calocedrus",
  "Washingtonia",
  "Sequoia",
  "Juglans",
  "Cocos",
  "Crataegus",
  "Sorbus",
  "Aesculus",
  "Phoenix",
  "Chilopsis",
  "Pseudotsuga",
  "Fagus",
  "Larix",
  "Ficus",
  "Ulmus",
  "Fremontodendron",
  "Cornus",
  "GenericDead",
  "Stump",
  "Unknown",
  "Sequoiadendron",
  "Agave",
  "Aralia",
  "Philodendron",
  "Cupressus",
  "Convallaria",
  "Pinus",
  "Rhamnus",
  "Sabal",
  "Cercocarpus",
  "Quercus Rubra",
  "Acer",
  "Picea",
  "Citrus",
  "Bulbophyllum",
  "Other",
  "Ligustrum",
  "Cordyline",
  "Parkinsonia",
  "Betula",
  "Chamaedorea",
  "Opuntia",
  "Alnus",
  "Carya",
  "Rhododendron",
  "Rosa",
  "Aiphanes",
  "Carnegiea",
  "Sassafras",
  "Pinus Sylvestris",
  "Yucca",
  "Amelanchier",
  "Sansevieria",
  "Magnolia",
  "Spartium",
  "Arbutus",
  "Acer Saccharum",
  "Helianthus",
  "Liquidambar",
  "Acacia",
  "Juniperus",
  "Fraxinus",
  "Quercus",
  "Populus",
  "Salix",
  "Hamamelis",
];

export const fillOptions: FillStyle[] = [
  "solid",
  "backward-diagonal",
  "cross",
  "diagonal-cross",
  "forward-diagonal",
  "horizontal",
  "none",
  "vertical",
];

export const fontDecorationOptions: FontDecoration[] = [
  "none",
  "underline",
  "line-through",
];

export const fonts = fontData;

export const fontFamilyOptions = [
  "Abril Fatface",
  "Alegreya",
  "Amarante",
  "Arial",
  "Atomic Age",
  "Audiowide",
  "Avenir Next LT Pro",
  "BellTopo Sans",
  "Belleza",
  "Black Ops One",
  "Cabin Sketch",
  "Coming Soon",
  "FGDC GeoAge",
  "Homemade Apple",
  "IM FELL DW Pica PRO",
  "Josefin Sans",
  "Just Another Hand",
  "Kranky",
  "Life Savers",
  "Loved by the King",
  "Merriweather",
  "Montserrat",
  "Noto Sans",
  "Noto Serif",
  "Old Standard TT",
  "Orbitron",
  "Oregano",
  "Oswald",
  "Pacifico",
  "Palatino Linotype",
  "Playfair Display",
  "Redressed",
  "Risque",
  "Roboto Condensed",
  "Rye",
  "Special Elite",
  "Syncopate Bold",
  "Syncopate",
  "Tangerine",
  "Ubuntu",
  "Ubuntu Mono",
  "UnifrakturCook",
  "Vast Shadow",
  "Walter Turncoat",
];

export const fontStyleOptions: FontStyle[] = ["normal", "italic", "oblique"];

export const fontWeightOptions: FontWeight[] = [
  "normal",
  "bold",
  "bolder",
  "lighter",
];

export const horizontalAlignmentOptions: TextHorizontalAlignment[] = [
  "center",
  "right",
  "left",
];

export const iconSymbol3dLayerAnchorOptions: IconSymbol3DLayerAnchor[] = [
  "center",
  "left",
  "right",
  "top",
  "bottom",
  "top-left",
  "top-right",
  "bottom-left",
  "bottom-right",
  "relative",
];

export const iconSymbol3dLayerResourcePrimitiveOptions: IconSymbol3DLayerPrimitive[] =
  ["circle", "square", "cross", "x", "kite", "triangle"];

export const joinOptions: LineJoin[] = ["miter", "round", "bevel"];

export const lineStyleMarker3dStyleOptions: LineMarkerStyle[] = [
  "arrow",
  "circle",
  "square",
  "diamond",
  "cross",
  "x",
];

export const lineStyleOptions: LineStyle[] = [
  "solid",
  "dash",
  "dash-dot",
  "dot",
  "long-dash",
  "long-dash-dot",
  "long-dash-dot-dot",
  "none",
  "short-dash",
  "short-dash-dot",
  "short-dash-dot-dot",
  "short-dot",
];

export const markerPlacementOptions: LineMarkerPlacement[] = [
  "begin",
  "end",
  "begin-end",
];

export const markerStyleOptions: LineMarkerStyle[] = [
  "arrow",
  "circle",
  "square",
  "diamond",
  "cross",
  "x",
];

export const objectSymbol3DLayerAnchorOptions: ObjectSymbol3DLayerAnchor[] = [
  "center",
  "top",
  "bottom",
  "origin",
  "relative",
];

export const objectSymbol3dLayerResourcePrimitiveOptions: ObjectSymbol3DLayerPrimitiveType[] =
  [
    "sphere",
    "cylinder",
    "cube",
    "cone",
    "inverted-cone",
    "diamond",
    "tetrahedron",
  ];

export const pathSymbol3dLayerAnchorOptions: PathSymbol3DLayerAnchor[] = [
  "center",
  "bottom",
  "top",
];

export const profileOptions: PathSymbol3DLayerProfile[] = ["quad", "circle"];

export const rotationOptions: PathSymbol3DLayerProfileRotation[] = [
  "all",
  "heading",
];

export const simpleMarkerSymbolStyleOptions: InstanceType<
  typeof SimpleMarkerSymbol
>["style"][] = [
  "circle",
  "square",
  "cross",
  "x",
  "diamond",
  "triangle",
  "path",
];

export const symbols = [
  {
    description:
      "CIMSymbols are high quality, scalable, multi-layer vector symbols for features and graphics.",
    line: true,
    link: "./cim-symbol/",
    map: true,
    mesh: false,
    name: "CIMSymbol",
    point: true,
    polygon: true,
    scene: true,
    symbolLayers: true,
  },
  {
    description:
      "LineSymbol3D is used to render features with Polyline geometry in a 3D Scene.",
    line: true,
    link: "./line-symbol-3d/",
    map: false,
    mesh: false,
    name: "LineSymbol3D",
    point: false,
    polygon: false,
    scene: true,
    symbolLayers: true,
  },
  {
    description:
      "MeshSymbol3D is used to render 3D mesh features in a SceneLayer in a 3D Scene.",
    line: false,
    link: "./mesh-symbol-3d/",
    map: false,
    mesh: true,
    name: "MeshSymbol3D",
    point: false,
    polygon: false,
    scene: true,
    symbolLayers: true,
  },
  {
    description:
      "PictureFillSymbol uses an image in a repeating pattern to symbolize polygon features in a 2D Map.",
    line: false,
    link: "./picture-fill-symbol/",
    map: true,
    mesh: false,
    name: "PictureFillSymbol",
    point: false,
    polygon: true,
    scene: false,
    symbolLayers: false,
  },
  {
    description:
      "PictureMarkerSymbol renders Point graphics in either a 2D Map or 3D Scene using an image.",
    line: false,
    link: "./picture-marker-symbol/",
    map: true,
    mesh: false,
    name: "PictureMarkerSymbol",
    point: true,
    polygon: false,
    scene: true,
    symbolLayers: false,
  },
  {
    description:
      "PointSymbol3D is used to render features with Point geometry in a 3D Scene.",
    line: false,
    link: "./point-symbol-3d/",
    map: false,
    mesh: false,
    name: "PointSymbol3D",
    point: true,
    polygon: false,
    scene: true,
    symbolLayers: true,
  },
  {
    description:
      "PolygonSymbol3D is used to render features with Polygon geometry in a 3D Scene.",
    line: false,
    link: "./polygon-symbol-3d/",
    map: false,
    mesh: false,
    name: "PolygonSymbol3D",
    point: false,
    polygon: true,
    scene: true,
    symbolLayers: true,
  },
  {
    description:
      "SimpleFillSymbol is used for rendering 2D polygons in either a Map or a Scene.",
    line: false,
    link: "./simple-fill-symbol/",
    map: true,
    mesh: false,
    name: "SimpleFillSymbol",
    point: false,
    polygon: true,
    scene: true,
    symbolLayers: false,
  },
  {
    description:
      "SimpleLineSymbol is used for rendering 2D polyline geometries in a 2D Map.",
    line: true,
    link: "./simple-line-symbol/",
    map: true,
    mesh: false,
    name: "SimpleLineSymbol",
    point: false,
    polygon: false,
    scene: true,
    symbolLayers: false,
  },
  {
    description:
      "SimpleMarkerSymbol is used for rendering 2D Point geometries with a simple shape and color in either a Map or a Scene.",
    line: false,
    link: "./simple-marker-symbol/",
    map: true,
    mesh: false,
    name: "SimpleMarkerSymbol",
    point: true,
    polygon: false,
    scene: true,
    symbolLayers: false,
  },
  {
    description:
      "Text symbols are used to define the graphic for displaying labels on a FeatureLayer, CSVLayer, Sublayer, and StreamLayer in a 2D Map.",
    line: false,
    link: "./text-symbol/",
    map: true,
    mesh: false,
    name: "TextSymbol",
    point: true,
    polygon: false,
    scene: false,
    symbolLayers: false,
  },
  {
    description:
      "WebStyleSymbol is a class used to conveniently create vector 2D symbols and realistic and thematic 3D symbols.",
    line: true,
    link: "./web-style-symbol/",
    map: true,
    mesh: false,
    name: "WebStyleSymbol",
    point: true,
    polygon: true,
    scene: true,
    symbolLayers: false,
  },
];

export const verticalAlignmentOptions: TextVerticalAlignment[] = [
  "baseline",
  "top",
  "middle",
  "bottom",
];

export const waterbodySizeOptions: WaterBodySize[] = [
  "small",
  "medium",
  "large",
];

export const waveStrengthOptions: WaveStrength[] = [
  "calm",
  "rippled",
  "slight",
  "moderate",
];

export const webStyleSymbols2DStyleOptions = ["Esri2DPointSymbolsStyle"];

export const webStyleSymbols3DStyleOptions = [
  "EsriIconsStyle",
  "EsriInfrastructureStyle",
  "EsriRealisticSignsandSignalsStyle",
  "EsriRealisticStreetSceneStyle",
  "EsriRealisticTransportationStyle",
  "EsriRealisticTreesStyle",
  "EsriRecreationStyle",
  "EsriThematicShapesStyle",
  "EsriThematicTreesStyle",
];
